# NOTE: Model initially generated by sqlacodegen from sensor-database_27-08-2026_prototyping.db.
# Run `uv run sqlacodegen "sqlite:///data/<file>.db" --generator declarative` to view code.

from typing import TYPE_CHECKING

from sqlalchemy import REAL, ForeignKey, Index, Integer
from sqlalchemy.orm import Mapped, mapped_column, relationship

from lift_ml.data.database.sensor_database import Base

if TYPE_CHECKING:
    from lift_ml.data.database.entity.session_entity import DbSession


class FullImuRaw(Base):
    __tablename__ = "full_imu_raw"
    __table_args__ = (Index("index_full_imu_raw_sessionId", "sessionId"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    session_id: Mapped[int] = mapped_column(
        "sessionId",
        ForeignKey("session.sessionId", onupdate="CASCADE", ondelete="CASCADE"),
        nullable=False,
    )
    ax: Mapped[float] = mapped_column(REAL, nullable=False)
    ay: Mapped[float] = mapped_column(REAL, nullable=False)
    az: Mapped[float] = mapped_column(REAL, nullable=False)
    gx: Mapped[float] = mapped_column(REAL, nullable=False)
    gy: Mapped[float] = mapped_column(REAL, nullable=False)
    gz: Mapped[float] = mapped_column(REAL, nullable=False)
    qx: Mapped[float] = mapped_column(REAL, nullable=False)
    qy: Mapped[float] = mapped_column(REAL, nullable=False)
    qz: Mapped[float] = mapped_column(REAL, nullable=False)
    qw: Mapped[float] = mapped_column(REAL, nullable=False)
    timestamp_us: Mapped[int] = mapped_column("timestampUs", Integer, nullable=False)

    session: Mapped["DbSession"] = relationship("DbSession", back_populates="full_imu_raw")
