# NOTE: Model initially generated by sqlacodegen from sensor-database_27-08-2026_prototyping.db.
# Run `uv run sqlacodegen "sqlite:///data/<file>.db" --generator declarative` to view code.
# some modification is done to keep idiomatic python like snake case for attributes

from typing import TYPE_CHECKING

from sqlalchemy import ForeignKey, Index, Integer, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from lift_ml.data.database.sensor_database import Base

if TYPE_CHECKING:
    from lift_ml.data.database.entity.session_entity import DbSession


class LiftContext(Base):
    __tablename__ = "lift_context"
    __table_args__ = (Index("index_lift_context_sessionId", "sessionId"),)

    session_id: Mapped[int] = mapped_column(
        "sessionId",
        ForeignKey("session.sessionId", onupdate="CASCADE", ondelete="CASCADE"),
        primary_key=True,
    )
    lift_category: Mapped[str] = mapped_column("liftCategory", Text, nullable=False)
    tempo: Mapped[str] = mapped_column(Text, nullable=False)
    rpe: Mapped[int | None] = mapped_column(Integer, nullable=True)

    session: Mapped["DbSession"] = relationship("DbSession", back_populates="lift_context")
