# NOTE: Model initially generated by sqlacodegen from sensor-database_27-08-2026_prototyping.db.
# Run `uv run sqlacodegen "sqlite:///data/<file>.db" --generator declarative` to view code.

from sqlalchemy import Text
from sqlalchemy.orm import Mapped, mapped_column

from lift_ml.data.database.sensor_database import Base


class LiftCategoryType(Base):
    __tablename__ = "lift_category_type"

    lift_category: Mapped[str] = mapped_column("liftCategory", Text, primary_key=True)


class MotionStateType(Base):
    __tablename__ = "motion_state_type"

    motion_state: Mapped[str] = mapped_column("motionState", Text, primary_key=True)


class SensorDataFormatType(Base):
    __tablename__ = "sensor_data_format_type"

    sensor_data_format: Mapped[str] = mapped_column("sensorDataFormat", Text, primary_key=True)


class TempoType(Base):
    __tablename__ = "tempo_type"

    tempo: Mapped[str] = mapped_column(Text, primary_key=True)
