# pyright: reportUnknownMemberType=false, reportUnknownVariableType=false, reportPrivateUsage=false
# NOTE: Model initially generated by sqlacodegen from sensor-database_27-08-2026_prototyping.db.
# Run `uv run sqlacodegen "sqlite:///data/<file>.db" --generator declarative` to view code.
# Modified to follow idiomatic Python naming and token-controlled creation.

from typing import Any

import pandas as pd
from sqlalchemy import Integer, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from lift_ml.data.database.entity.full_imu_raw_entity import FullImuRaw
from lift_ml.data.database.entity.lift_context_entity import LiftContext
from lift_ml.data.database.sensor_database import Base
from lift_ml.data.domain.session import _SESSION_CREATION_TOKEN, Session


# sqlacodegen name was Session. Renamed to DbSession to seperate from domain layer
class DbSession(Base):
    __tablename__ = "session"

    session_id: Mapped[int] = mapped_column(
        "sessionId", Integer, primary_key=True, autoincrement=True
    )
    start_time: Mapped[int] = mapped_column("startTime", Integer, nullable=False)
    motion_state: Mapped[str] = mapped_column("motionState", Text, nullable=False)
    sensor_data_format: Mapped[str] = mapped_column("sensorDataFormat", Text, nullable=False)
    end_time: Mapped[int | None] = mapped_column("endTime", Integer, nullable=True)

    full_imu_raw: Mapped[list[FullImuRaw]] = relationship(
        "FullImuRaw",
        back_populates="session",
        cascade="all, delete-orphan",
        order_by="FullImuRaw.id",
    )
    lift_context: Mapped[LiftContext | None] = relationship(
        "LiftContext",
        back_populates="session",
        uselist=False,
        cascade="all, delete-orphan",
    )

    def to_session(self) -> Session:
        """Converts the database entity into a domain Session object."""

        records: list[dict[str, Any]] = [
            {
                "ax": row.ax,
                "ay": row.ay,
                "az": row.az,
                "gx": row.gx,
                "gy": row.gy,
                "gz": row.gz,
                "qx": row.qx,
                "qy": row.qy,
                "qz": row.qz,
                "qw": row.qw,
                "timestampUs": row.timestamp_us,
            }
            for row in self.full_imu_raw
        ]

        df = pd.DataFrame(records)

        metadata: dict[str, Any] = {
            "sessionId": self.session_id,
            "startTime": self.start_time,
            "endTime": self.end_time,
            "motionState": self.motion_state,
            "sensorDataFormat": self.sensor_data_format,
        }

        if self.lift_context is not None:
            metadata["liftCategory"] = self.lift_context.lift_category
            metadata["tempo"] = self.lift_context.tempo
            metadata["rpe"] = self.lift_context.rpe

        return Session(
            _token=_SESSION_CREATION_TOKEN,
            session_id=self.session_id,
            sensor_data=df,
            motion_state=self.motion_state,
            sensor_data_format=self.sensor_data_format,
            metadata=metadata,
        )
